matrix:
  include:
    # - language: python
    #   python: 2.7
    #   os: linux
    # - language: python
    #   python: 3.4
    #   os: linux
    # - language: python
    #   python: nightly
    #   os: linux
    # - language: python
    #   python: pypy
    #   os: linux
    - language: generic
      os: osx
      env: PYTHON_VERSION=2.7
    # - language: generic
    #   os: osx
    #   env: PYTHON_VERSION=3.4.3

install:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; sudo apt-get install -qq xclip; pip install --editable .; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; brew outdated pyenv || brew upgrade pyenv; brew install pyenv-virtualenv; eval "$(pyenv init -)"; pyenv install ${PYTHON_VERSION}; pyenv virtualenv ${PYTHON_VERSION} xerox; pyenv rehash; pyenv activate xerox; sudo pip install --editable .; fi

before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export DISPLAY=:99.0; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sh -e /etc/init.d/xvfb start; fi

script: python test_xerox.py
