os:
  - linux
  # - osx
language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"

install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq xclip"
  - "pip install --editable ."

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: python test_xerox.py
